<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Sparsh\ReferrerUrlTracking\Block\ReferrerUrl $block */
?>
<?php if ($block->getReferrerUrl() && $block->isEnableCustomerReferrerUrl()) : ?>
    <div class="field">
        <div class="control">
            <input type="hidden" name="referrer_url" id="referrer_url" value="<?= /* @noEscape */ trim($block->getReferrerUrl()) ?>">
        </div>
    </div>
<?php endif; ?>
