<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Element\Template $block */
?>
<?php
$helper = $this->helper('Sparsh\ReferrerUrlTracking\Helper\Data');
$isEnabledCustomerTracking = $helper->isEnableCustomerReferrerUrl();
$isEnabledOrderTracking = $helper->isEnableOrderReferrerUrl();

if ($isEnabledOrderTracking || $isEnabledCustomerTracking) :
    ?>
    <script>
        require(["jquery", "jquery/ui"],
            function($){
                $(document).ready(function () {
                    var referrerUrl = document.referrer;
                    var baseUrl = "<?= /* @noEscape */ $block->getBaseUrl(); ?>";
                    if(!referrerUrl.includes(baseUrl)){
                        $.ajax({
                            type: "POST",
                            url: "<?= /* @noEscape */ $block->getUrl('sparsh_referrer_url') ?>",
                            data: {
                                url:referrerUrl
                            }
                        });
                    }
                });
            });
    </script>
<?php endif; ?>
